<?php
require_once __DIR__ . '/vendor/autoload.php';

$mpdf = new \Mpdf\Mpdf([
	'default_font_size' => 14,
	'default_font' => 'gotham'
]);

$today = date(" j / M / Y ");
$dm= date("F / Y");
$date=date("W");
$dueDate = date("j / M / Y ",strtotime("+30 days"));
date_default_timezone_set("Asia/Bangkok");

$nokhtml = '
<style>
body {
	font-family: gotham;
	font-size: 14px;
	padding :0; margin: 0;
}
.row{
	clear:both;
	overflow:hidden;
}

.col1 {
	float:left;
	width:60%;
}
.col2 {
	float:right;
	width:30%;
}
h1, h2, h3, h4, h5, h6 {
padding: 0;
margin : 0;
}

.floatleft{
	float:left;
}

.floatright{
	float:right;
}
table {
	font-family: gotham;
	border-collapse: collapse;
	width: 100%;
    
  }
  
  td, th {
	border: 1px solid #b9e5fb;
	text-align: center;
	padding: 8px;
  }
 
  .items td.blanktotal {
    background-color: #FFFFFF;
    border: 0mm none #FFFFFF;
    border-top: 0.1mm solid #FFFFFF;
    border-right: 0.1mm solid #FFFFFF;
	text-align: left;
}
.items td.totals {
    text-align: right;
}
  </style>



<body>


<htmlpagefooter name="myfooter">
<div style="border-top: 1px solid #333333; font-size: 9pt; text-align: center; padding-top: 1mm; ">
Page {PAGENO} of {nb}
</div>
</htmlpagefooter>

<sethtmlpageheader name="myheader" value="on" show-this-page="1" />
<sethtmlpagefooter name="myfooter" value="on" />


<div class="row">
<div class="col1">
<img src="img/tenth.png" width="240"  />

<p>Tenthmatrix Ltd. ,The Coach House, 77A Marlowes <br />Hemel Hempstead Herts, HP1 1LF<br />Email: billing@tenthmatrix.co.uk<br />Tel: 44 1442 384 149</p>


</div>

<div class="col2 floatright">
<img src="img/iv6.png" width="200"  />
</div>

<div class="row" style="border: 1px solid #00a9d3; padding: 20px;">
<div class="col1">

<div class="name"><h3>INVOICE TO :name customer</h3></div>

<div class="address"><h3>ADDRESS : Thai</h3></div>
<div class="tel"><h3>TEL : 000 000 0000</h3></div>
<div class="email"><h3>EMAIL : customer@gmail.com</h3></div>
</div>

<div class="col2 floatright">
<div class="invoice no"><h3>INVOICE NO: ws-0001</h3></div> 
<div class="date"><h3>DATE : '.$today.'</h3></div>
<div class="due date"><h3>DUE DATE : '.$dueDate.'</h3></div>
<div class="totals"><h3>TOTAL : &#163;00000</h3></div>
</div>
</div>

<br />
<table class="items">
<tr>
<th width="10%">No</th>
<th width="50%">Description </th>
<th width="10%">Unit</th>
<th width="15%">Unit price</th>
<th width="15%">Total</th>
</tr>

<tr>
<td>1</td>
<td>small website design-one page website (Free hosting and domain name for the first year)</td>
<td>1</td>
<td>&#163;000 </td>
<td>&#163;000 </td>
</tr>

<tr>
<td class="blanktotal" colspan="3" rowspan="6" >
</td>

</tr>

<tr>
<td class="totals">subtotal (excl. VAT):</td>
<td class="totals" style="background-color: #b9e5fb;">&#163;000 </td>
</tr>

<tr>
<td class="totals">VAT 21,00%:</td>
<td class="totals" style="background-color: #b9e5fb;">&#163;</td>
</tr>

<tr>
<td class="totals" style="background-color: #00a9d3; color: #fff;"><b>Total:</b></td>
<td class="totals" style="background-color: #00a9d3; color: #fff;"><b>&#163;0000 </b></td>
</tr>

</table>

<p><b>Thank you for your business!</b><br />VAT No.972 9855 56. Bank: HSBC,Sort Code: 40-24-07 ,Account No.91565850</p>
<p><b> terms:</b>Please note that our payment terms for this Invoice are NET 15. Interest will be charged on all Invoice that are not paid on time.</p>
<p><b>Please make payment by electronic transfer to :</b><br /> 

<table class="detail">
<tr>
<td >Bank name :</td>
<td >Tide</td>
</tr>

<tr>
<td >Account name :</td>
<td >Tenmatrix Ltd</td>
</tr>

<tr>
<td>Sort code :</td>
<td>23-69-72</td>
</tr>

<tr>
<td>Account number :</td>
<td>16279782</td>
</tr>

<tr>
<td>Please use reference :</td>
<td>IT CONSUTING-1415</td>
</tr>

</table>

<br />
<p>Tenmatrix Ltd UK.also trading as Tenmatrix,is a registered company number:11641870. VAT number: GB 361 746 193. Registered in England and Wales. Registered office address: The Coach House,77A Marlowes, Hemel Hempstead, Herts, United Kingdom,HP1 1LF.</p>

<p><b>Note:</b>This Invoice was generated by  Workstation CRM and Invoicing system automatically.</p>
<div class="date">Date: '.$today.'</div>
<div class="time"> Time: '. date("h:i:sa").'</div>

</body>';


//

$mpdf->WriteHTML($nokhtml . $termsHTML);


//

$mpdf->Output();


?>